# Generated by Django 5.0.4 on 2024-04-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_formfootercontact_delete_comment_delete_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_popup', models.CharField(max_length=20)),
                ('phone_popup', models.CharField(max_length=11)),
            ],
        ),
    ]
