# Generated by Django 5.0.4 on 2024-04-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_formpopup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormPopup',
        ),
    ]
