# Generated by Django 5.0.4 on 2024-04-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0006_formfootercontact_delete_contactrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFooter_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_footer', models.CharField(max_length=11)),
            ],
        ),
    ]
