# Generated by Django 5.0.4 on 2024-04-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0007_formfooter_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfootercontact',
            old_name='name',
            new_name='name_under_footer',
        ),
        migrations.RenameField(
            model_name='formfootercontact',
            old_name='phone',
            new_name='phone_under_footer',
        ),
    ]
