# Generated by Django 5.0.4 on 2024-04-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0008_rename_name_formfootercontact_name_under_footer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_popup', models.CharField(max_length=50)),
                ('phone_popup', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='FormFooter_page',
        ),
        migrations.AlterField(
            model_name='formfootercontact',
            name='phone_under_footer',
            field=models.CharField(max_length=20),
        ),
    ]
